### ISSUE TITLE
Improve Api Error Handling

### ISSUE THREAD

**Issue by jamsinclair** [idanlo/react-spotify-api#22]
@idanlo Thanks for the great work on this project! 

Using the library I noticed it does not set an error state when the API returns a non-200 status code. The error JSON data is returned in the `data` field. 

Reproduction:
```jsx
import { SpotifyApiContext, Artist } from 'react-spotify-api';

<SpotifyApiContext.Provider value="bad_access_token">
  <Artist id="6eUKZXaKkcviH0Ku9w2n3V">
    {(artist, loading, error) => (
      <div>
        <p>Artist: {JSON.stringify(artist)}</p>
        <p>Error: {JSON.stringify(error)}</p>
        <p>Loading: {JSON.stringify(loading)}</p>
      </div>
    )}
  </Artist>
</SpotifyApiContext.Provider>
```
Result:
```
Artist: {"error":{"status":401,"message":"Invalid access token"}}

Error: false

Loading: false
```

I would like to propose setting an error object when encountered with the API or at the very least set to `true`. Do you have any thoughts on this? Happy to help 😄

**Comment by idanlo** [comment]
@jamsinclair https://github.com/idanlo/react-spotify-api/commit/cfc85f4b6853e1f08a614754688c461762750e26 this commit should fix it. I just released version 2.0.1 with this fix. 
Please update if it works as it should

**Comment by jamsinclair** [comment]
Thanks @idanlo, beat me to it! That solution does work for me.

I've made a PR over in #23 that also sets the error object in the state. I'm happy either way.

**Comment by idanlo** [comment]
Thanks @jamsinclair I actually already made some changes but you have some interesting stuff with the `res.status` which I will implement. Also the testing you wrote - 👍

**Comment by idanlo** [comment]
Thank you @jamsinclair, this is now fixed and all tests are passing.
I will close your pull request
