### ISSUE TITLE
I cannot seem to make any component working

### ISSUE THREAD

**Issue by MagicMustache** [idanlo/react-spotify-api#280]
When i try to implement any example component from the docs it never works. What am I doing wrong ?
Here's one of my component 
```
import React from 'react';
import {Playlist} from "react-spotify-api"

function PlaylistComponent(props) {
    return (
        <Playlist id={props.id}>
            {({playlist}) => {
                return playlist ? <h3>{playlist.name}</h3> : null
            }}
        </Playlist>
    )
}

export default PlaylistComponent
```

**Comment by kahramanbayraktar** [comment]
I am having the same issue. The data is fetched from Spotify -- it can be observed via the React Developer Tools -- but it is never rendered on the page. This issue appears only when components are used. With hooks, it seems working well.

In my case, I was able to render user profile info with useUser Hook. However, I couldn't make it render data with Artist and UserPlaylists components.

**Comment by kahramanbayraktar** [comment]
I solved my problem. The sample code in the [documentation](https://idanlo.github.io/react-spotify-api/#userplaylists) was wrong -- probably outdated. It must be:

```
import { UserPlaylists } from 'react-spotify-api';

function Playlists() {
  return (
    <UserPlaylists>
      {(playlists, loading, error) =>
        playlists
          ? playlists.data.items.map((playlist) => (
              <h1 key={playlist.id}>{playlist.name}</h1>
            ))
          : null
      }
    </UserPlaylists>
  );
}

export default Playlists;
```

What I did is adding `data` into
`playlists.items.map`
so that it became
`playlists.data.items.map`

**Comment by kahramanbayraktar** [comment]
Even I needed to check if the data is loaded:

```
!playlists.loading && playlists.data
? playlists.data.items.map((playlist) => (<h1 key={playlist.id}>{playlist.name}</h1>))
: <h1>Loading...</h1>
```

**Comment by MagicMustache** [comment]
Ok that's great, thanks for your help !
