### ISSUE TITLE
Distribution build uses a regeneratorRuntime function that doesn't exist

### ISSUE THREAD

**Issue by samjt** [idanlo/react-spotify-api#7]
Hi,

It looks like you're using `regeneratorRuntime` in the compiled `useApiRequest.js`, probably via compilation from Babel.
From `dist/ApiRequest/useApiRequest.js`
```js
function _loadData() {
    _loadData = _asyncToGenerator(regeneratorRuntime.mark(function _callee() {
      var res, _data;

      return regeneratorRuntime.wrap(function _callee$(_context) {
...
```

But regeneratorRuntime itself is not defined nor imported.
I think that you need to update your .babelrc to include an extra babel plugin

**Comment by samjt** [comment]
I've opened a pr here @idanlo 
#8

**Comment by idanlo** [comment]
Thanks. I'll merge that

**Comment by idanlo** [comment]
@samjt  I released a new version. Tell me if that works for you

**Comment by samjt** [comment]
@idanlo Yes, works great now! Thanks for the quick release.
